[package]
name = "vgpu-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.10.9"
futures = "0.3"
tokio = { version = "1.13.0", features = ["rt-multi-thread"] }
chrono = "0.4.19"
serde_json = "1.0.69"