[package]
name = "vgpu-ci"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.10.9"
tokio = { version = "1.13.0", features = ["rt-multi-thread"] }
serde = "1.0.130"
serde_json = "1.0.69"
hyper = { version = "0.14.14", features = ["server"] }
